######################################################################
# Automatically generated by qmake (2.01a) lun. févr. 27 20:24:18 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include
INCLUDEPATH += . include

# Input
HEADERS += Display.h \
           Lidar.h \
           include/rplidar.h \
           include/rplidar_cmd.h \
           include/rplidar_driver.h \
           include/rplidar_protocol.h \
           include/rptypes.h
SOURCES += Display.cpp Lidar.cpp main.cpp
