######################################################################
# Automatically generated by qmake (2.01a) mar. mars 28 21:04:11 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Display.h
SOURCES += Display.cpp main.cpp
